### ISSUE TITLE
Opening the project

### ISSUE THREAD

**Issue by Frank-en-stein** [Gjohnson6/SpaceCombat#1]
I tried to open this project in unreal 4.16.2 and i got was the minimal default template that unreal provides.   Can you address this issue, please?

**Comment by Gjohnson6** [comment]
I haven't been able to work on this much recently so the project was still built for UE 4.14. You can try right clicking SpaceCombat.uproject then clicking "Switch Unreal Engine version" and selecting 4.16. 

I also changed the project to 4.16.3 on my end and pushed that as well as some other small changes I made in the last couple of weeks (and a bunch of starter content on accident, oops) just now so you can also pull again and hopefully it should work, Let me know if it's still broken. Also fair warning, this project in it's current state is less of a game and more me messing around with UE to get the hang of things so it's pretty messy.

**Comment by Frank-en-stein** [comment]
Got is working. All i'm doing is trying to learn Unreal 4. Thank you for your feedback. Cheers
